import type { StorefrontListing, Deal, CustomerReview, StorefrontCategory } from "@/types/database";

export const MOCK_CATEGORIES: StorefrontCategory[] = [
  { id: "1", name: "Electronics", slug: "electronics", parent_id: null, description: "Smartphones, gadgets, accessories & more", image_url: "/categories/electronics.jpg", icon_name: "Smartphone", display_order: 1, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "2", name: "Home & Kitchen", slug: "home-kitchen", parent_id: null, description: "Appliances, decor, cookware & furniture", image_url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop", icon_name: "Home", display_order: 2, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "3", name: "Fashion", slug: "fashion", parent_id: null, description: "Clothing, shoes, bags & accessories", image_url: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop", icon_name: "Shirt", display_order: 3, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "4", name: "Beauty & Health", slug: "beauty-health", parent_id: null, description: "Skincare, makeup, wellness & supplements", image_url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop", icon_name: "Heart", display_order: 4, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "5", name: "Sports & Outdoors", slug: "sports-outdoors", parent_id: null, description: "Fitness gear, camping, sports equipment", image_url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=300&fit=crop", icon_name: "Dumbbell", display_order: 5, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "6", name: "Toys & Games", slug: "toys-games", parent_id: null, description: "Kids toys, board games, puzzles & fun", image_url: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=300&fit=crop", icon_name: "Gamepad2", display_order: 6, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "7", name: "Automotive", slug: "automotive", parent_id: null, description: "Car accessories, tools & maintenance", image_url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=300&fit=crop", icon_name: "Car", display_order: 7, is_active: true, seo_title: null, seo_description: null, created_at: "" },
  { id: "8", name: "Garden & DIY", slug: "garden-diy", parent_id: null, description: "Tools, plants, outdoor furniture & more", image_url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop", icon_name: "Flower2", display_order: 8, is_active: true, seo_title: null, seo_description: null, created_at: "" },
];

export const MOCK_LISTINGS: StorefrontListing[] = [
  {
    id: "l1", product_id: "p1", title: "Fast Charger - Type-C Cable and Adapter", description: "High-speed 25W USB-C fast charger compatible with Samsung, Huawei, Xiaomi and all Android devices. Includes 1m braided cable.", category: "Electronics", slug: "fast-charger-type-c", images: ["https://media.takealot.com/covers_images/78d73b16b0e741e8b7172f4f8df9abfc/s-zoom.file", "https://media.takealot.com/covers_images/78d73b16b0e741e8b7172f4f8df9abfc/s-fb.file"], current_price: 129, original_price: 199, sku: "SB-034449", stock_quantity: 50, is_in_stock: true, rating_average: 4.3, rating_count: 127, tags: ["charger", "usb-c", "fast-charging"], attributes: { "Wattage": "25W", "Cable Length": "1m", "Connector": "USB-C" }, brand: "ShopMO", status: "live", created_at: "2026-03-06", updated_at: "2026-03-06"
  },
  {
    id: "l2", product_id: "p2", title: "Wireless Bluetooth Earbuds Pro", description: "True wireless earbuds with active noise cancellation, 30-hour battery life, IPX5 waterproof. Crystal clear calls and deep bass.", category: "Electronics", slug: "wireless-bluetooth-earbuds-pro", images: ["https://media.takealot.com/covers_images/39225178a9dd4200897872d3f2a9894e/s-zoom.file", "https://media.takealot.com/covers_images/39225178a9dd4200897872d3f2a9894e/s-fb.file"], current_price: 299, original_price: 499, sku: "SB-EAR001", stock_quantity: 35, is_in_stock: true, rating_average: 4.6, rating_count: 89, tags: ["earbuds", "wireless", "bluetooth", "anc"], attributes: { "Battery": "30 hours", "Waterproof": "IPX5", "ANC": "Yes" }, brand: "ShopMO", status: "live", created_at: "2026-03-01", updated_at: "2026-03-10"
  },
  {
    id: "l3", product_id: "p3", title: "Smart Watch Fitness Tracker", description: "Full-touch display smartwatch with heart rate monitor, blood oxygen, sleep tracking. 100+ sport modes. Works with Android & iOS.", category: "Electronics", slug: "smart-watch-fitness-tracker", images: ["https://media.takealot.com/covers_images/1c051bd88958492a8158f325cf0723dc/s-zoom.file", "https://media.takealot.com/covers_images/1c051bd88958492a8158f325cf0723dc/s-fb.file"], current_price: 349, original_price: 599, sku: "SB-WAT001", stock_quantity: 20, is_in_stock: true, rating_average: 4.4, rating_count: 203, tags: ["smartwatch", "fitness", "health"], attributes: { "Display": "1.85 inch", "Battery": "7 days", "Waterproof": "IP68" }, brand: "ShopMO", status: "live", created_at: "2026-02-15", updated_at: "2026-03-10"
  },
  {
    id: "l4", product_id: "p4", title: "Portable Bluetooth Speaker 20W", description: "Powerful 20W portable speaker with 360-degree surround sound. 12-hour playtime, IPX7 waterproof. Perfect for braai, pool and outdoor.", category: "Electronics", slug: "portable-bluetooth-speaker-20w", images: ["https://media.takealot.com/covers_images/76b8ab91e2b2417d9f6a4be26d7ce463/s-zoom.file", "https://media.takealot.com/covers_images/76b8ab91e2b2417d9f6a4be26d7ce463/s-fb.file"], current_price: 399, original_price: 649, sku: "SB-SPK001", stock_quantity: 15, is_in_stock: true, rating_average: 4.7, rating_count: 156, tags: ["speaker", "bluetooth", "portable", "waterproof"], attributes: { "Power": "20W", "Battery": "12 hours", "Waterproof": "IPX7" }, brand: "ShopMO", status: "live", created_at: "2026-02-20", updated_at: "2026-03-08"
  },
  {
    id: "l5", product_id: "p5", title: "LED Ring Light 10 inch with Tripod", description: "Professional 10-inch ring light with adjustable tripod stand and phone holder. 3 colour modes, 10 brightness levels. Perfect for TikTok, YouTube and video calls.", category: "Electronics", slug: "led-ring-light-10-inch-tripod", images: ["https://media.takealot.com/covers_tsins/59159092/59159092-1-zoom.png", "https://media.takealot.com/covers_tsins/59159092/59159092-1-fb.png"], current_price: 279, original_price: 449, sku: "SB-RNG001", stock_quantity: 40, is_in_stock: true, rating_average: 4.5, rating_count: 312, tags: ["ring-light", "tripod", "content-creation"], attributes: { "Size": "10 inch", "Modes": "3 colours", "Height": "160cm" }, brand: "ShopMO", status: "live", created_at: "2026-01-20", updated_at: "2026-03-05"
  },
  {
    id: "l6", product_id: "p6", title: "Electric Kettle 1.8L Stainless Steel", description: "Fast-boil 1500W electric kettle with auto shut-off and boil-dry protection. BPA-free, stainless steel interior.", category: "Home & Kitchen", slug: "electric-kettle-1-8l", images: ["https://media.takealot.com/covers_images/09d473293cfb4fca961242e978a9bb19/s-zoom.file", "https://media.takealot.com/covers_images/09d473293cfb4fca961242e978a9bb19/s-fb.file"], current_price: 249, original_price: 399, sku: "SB-KET001", stock_quantity: 25, is_in_stock: true, rating_average: 4.2, rating_count: 78, tags: ["kettle", "kitchen", "appliance"], attributes: { "Capacity": "1.8L", "Power": "1500W", "Material": "Stainless Steel" }, brand: "ShopMO", status: "live", created_at: "2026-02-01", updated_at: "2026-03-10"
  },
  {
    id: "l7", product_id: "p7", title: "Air Fryer 5.5L Digital", description: "Large capacity 5.5L digital air fryer with 8 preset cooking programs. Cook healthier meals with up to 85% less oil. Non-stick basket.", category: "Home & Kitchen", slug: "air-fryer-5-5l-digital", images: ["https://media.takealot.com/covers_images/06523bdbf064409284a815996b193c61/s-zoom.file", "https://media.takealot.com/covers_images/06523bdbf064409284a815996b193c61/s-fb.file"], current_price: 999, original_price: 1599, sku: "SB-FRY001", stock_quantity: 10, is_in_stock: true, rating_average: 4.8, rating_count: 445, tags: ["air-fryer", "kitchen", "healthy-cooking"], attributes: { "Capacity": "5.5L", "Programs": "8 presets", "Power": "1700W" }, brand: "ShopMO", status: "live", created_at: "2026-01-15", updated_at: "2026-03-12"
  },
  {
    id: "l8", product_id: "p8", title: "Yoga Mat Premium 6mm Non-Slip", description: "Professional 6mm thick yoga mat with alignment lines. Non-slip surface, eco-friendly TPE material. Includes carry strap.", category: "Sports & Outdoors", slug: "yoga-mat-premium-6mm", images: ["https://media.takealot.com/covers_images/9889705fa7bf44cabebac3b55393d85f/s-zoom.file", "https://media.takealot.com/covers_images/9889705fa7bf44cabebac3b55393d85f/s-fb.file"], current_price: 179, original_price: 299, sku: "SB-YOG001", stock_quantity: 30, is_in_stock: true, rating_average: 4.3, rating_count: 67, tags: ["yoga", "fitness", "mat"], attributes: { "Thickness": "6mm", "Material": "TPE", "Length": "183cm" }, brand: "ShopMO", status: "live", created_at: "2026-02-10", updated_at: "2026-03-10"
  },
  {
    id: "l9", product_id: "p9", title: "Resistance Bands Set of 5", description: "Professional latex resistance bands set with 5 levels. Perfect for home workouts, physio recovery and stretching. Includes door anchor and carry bag.", category: "Sports & Outdoors", slug: "resistance-bands-set-5", images: ["https://media.takealot.com/covers_images/efc016586601450598dd8ab1c0c327d0/s-zoom.file", "https://media.takealot.com/covers_images/efc016586601450598dd8ab1c0c327d0/s-fb.file"], current_price: 129, original_price: 249, sku: "SB-BND001", stock_quantity: 45, is_in_stock: true, rating_average: 4.6, rating_count: 189, tags: ["resistance-bands", "fitness", "home-workout"], attributes: { "Levels": "5 (2-30kg)", "Material": "Natural Latex" }, brand: "ShopMO", status: "live", created_at: "2026-02-05", updated_at: "2026-03-08"
  },
  {
    id: "l10", product_id: "p10", title: "Insulated Water Bottle 750ml", description: "Double-wall vacuum insulated stainless steel water bottle. Keeps drinks cold 24hrs or hot 12hrs. Leak-proof lid, BPA-free.", category: "Sports & Outdoors", slug: "insulated-water-bottle-750ml", images: ["https://media.takealot.com/covers_images/d72d4ed33d9342d79d1a4719c7cc8edc/s-zoom.file", "https://media.takealot.com/covers_images/d72d4ed33d9342d79d1a4719c7cc8edc/s-fb.file"], current_price: 149, original_price: 249, sku: "SB-BTL001", stock_quantity: 55, is_in_stock: true, rating_average: 4.5, rating_count: 234, tags: ["water-bottle", "insulated", "stainless-steel"], attributes: { "Capacity": "750ml", "Material": "Stainless Steel", "Insulation": "24hr cold / 12hr hot" }, brand: "ShopMO", status: "live", created_at: "2026-01-25", updated_at: "2026-03-06"
  },
  {
    id: "l11", product_id: "p11", title: "Vitamin C Serum with Hyaluronic Acid", description: "Premium 30ml Vitamin C face serum with hyaluronic acid and vitamin E. Brightens skin, reduces dark spots, anti-aging formula.", category: "Beauty & Health", slug: "vitamin-c-serum-hyaluronic", images: ["https://media.takealot.com/covers_images/dd46bee1a5584a6dba14f88479509aa9/s-zoom.file", "https://media.takealot.com/covers_images/dd46bee1a5584a6dba14f88479509aa9/s-fb.file"], current_price: 149, original_price: 299, sku: "SB-SER001", stock_quantity: 60, is_in_stock: true, rating_average: 4.4, rating_count: 178, tags: ["skincare", "vitamin-c", "serum", "anti-aging"], attributes: { "Size": "30ml", "Key Ingredients": "Vitamin C, Hyaluronic Acid, Vitamin E" }, brand: "ShopMO", status: "live", created_at: "2026-02-12", updated_at: "2026-03-10"
  },
  {
    id: "l12", product_id: "p12", title: "Car Phone Mount Magnetic Dashboard", description: "Strong magnetic car phone mount for dashboard. 360-degree rotation, one-hand operation. Compatible with all smartphones. Easy install, no tools needed.", category: "Automotive", slug: "car-phone-mount-magnetic", images: ["https://media.takealot.com/covers_images/e19be70d4d434ab881e571c3126fa84c/s-zoom.file", "https://media.takealot.com/covers_images/e19be70d4d434ab881e571c3126fa84c/s-fb.file"], current_price: 89, original_price: 179, sku: "SB-MNT001", stock_quantity: 70, is_in_stock: true, rating_average: 4.1, rating_count: 95, tags: ["car-mount", "phone-holder", "magnetic"], attributes: { "Type": "Magnetic", "Rotation": "360 degree", "Install": "Dashboard" }, brand: "ShopMO", status: "live", created_at: "2026-02-18", updated_at: "2026-03-09"
  },
  {
    id: "l13", product_id: "p13", title: "Volkano Scorpio True Wireless Earphones", description: "Volkano Scorpio true wireless earphones with Bluetooth 5.0, touch controls, and compact charging case. Up to 20 hours total playtime. Perfect for gym, commute, and everyday use.", category: "Electronics", slug: "volkano-scorpio-true-wireless-earphones", images: ["https://media.takealot.com/covers_images/df1ece2555f04882a0c5f611ea721f8c/s-zoom.file", "https://media.takealot.com/covers_images/df1ece2555f04882a0c5f611ea721f8c/s-fb.file"], current_price: 229, original_price: 399, sku: "SB-VLK001", stock_quantity: 40, is_in_stock: true, rating_average: 4.6, rating_count: 2965, tags: ["earphones", "wireless", "bluetooth", "volkano"], attributes: { "Bluetooth": "5.0", "Battery": "20 hours total", "Type": "True Wireless" }, brand: "ShopMO", status: "live", created_at: "2026-03-01", updated_at: "2026-03-12"
  },
  {
    id: "l14", product_id: "p14", title: "soundcore R50i True Wireless Earbuds", description: "Anker soundcore R50i with 10mm drivers, custom EQ via app, 30-hour playtime, and IPX5 water resistance. Lightweight and comfortable for all-day wear.", category: "Electronics", slug: "soundcore-r50i-true-wireless-earbuds", images: ["https://media.takealot.com/covers_images/f97b79a936af45b9a9a16afeb927a8ca/s-zoom.file", "https://media.takealot.com/covers_images/f97b79a936af45b9a9a16afeb927a8ca/s-fb.file"], current_price: 499, original_price: 749, sku: "SB-SNC001", stock_quantity: 25, is_in_stock: true, rating_average: 4.7, rating_count: 1522, tags: ["earbuds", "wireless", "soundcore", "anker"], attributes: { "Driver": "10mm", "Battery": "30 hours", "Waterproof": "IPX5" }, brand: "ShopMO", status: "live", created_at: "2026-03-02", updated_at: "2026-03-13"
  },
  {
    id: "l15", product_id: "p15", title: "WINX GO 10000mAh Power Bank", description: "WINX GO compact 10000mAh power bank with dual USB output, LED battery indicator, and slim design. Charges two devices simultaneously. Essential for load shedding.", category: "Electronics", slug: "winx-go-10000mah-power-bank", images: ["https://media.takealot.com/covers_images/77fd0368bba64a5885bc1dbd1c8b16a7/s-zoom.file", "https://media.takealot.com/covers_images/77fd0368bba64a5885bc1dbd1c8b16a7/s-fb.file"], current_price: 159, original_price: 249, sku: "SB-WNX001", stock_quantity: 65, is_in_stock: true, rating_average: 4.6, rating_count: 392, tags: ["power-bank", "portable-charger", "load-shedding"], attributes: { "Capacity": "10000mAh", "Outputs": "Dual USB", "Weight": "220g" }, brand: "ShopMO", status: "live", created_at: "2026-03-03", updated_at: "2026-03-11"
  },
  {
    id: "l16", product_id: "p16", title: "40000mAh Power Bank 22.5W Fast Charging", description: "Massive 40000mAh power bank with 22.5W fast charging, digital display, and built-in cables. Type-C and Lightning compatible. Your ultimate load shedding backup.", category: "Electronics", slug: "40000mah-power-bank-fast-charging", images: ["https://media.takealot.com/covers_images/f77c2e4ee6054df79d37ef4589bc099c/s-zoom.file", "https://media.takealot.com/covers_images/f77c2e4ee6054df79d37ef4589bc099c/s-fb.file"], current_price: 549, original_price: 849, sku: "SB-PWR002", stock_quantity: 30, is_in_stock: true, rating_average: 4.4, rating_count: 203, tags: ["power-bank", "fast-charging", "load-shedding", "high-capacity"], attributes: { "Capacity": "40000mAh", "Fast Charge": "22.5W", "Display": "Digital LED" }, brand: "ShopMO", status: "live", created_at: "2026-03-04", updated_at: "2026-03-12"
  },
  {
    id: "l17", product_id: "p17", title: "4K Dash Cam with 64GB SD Card", description: "Ultra HD 4K dash camera with 64GB SD card included. Wide-angle lens, night vision, loop recording, and G-sensor. Protect yourself on SA roads.", category: "Automotive", slug: "4k-dash-cam-64gb-sd-card", images: ["https://media.takealot.com/covers_images/055f49fc33ac4b2e8b42a270cee57fdf/s-zoom.file", "https://media.takealot.com/covers_images/055f49fc33ac4b2e8b42a270cee57fdf/s-fb.file"], current_price: 799, original_price: 1199, sku: "SB-DSH001", stock_quantity: 18, is_in_stock: true, rating_average: 4.5, rating_count: 123, tags: ["dash-cam", "car-camera", "4k", "road-safety"], attributes: { "Resolution": "4K UHD", "Storage": "64GB included", "Night Vision": "Yes" }, brand: "ShopMO", status: "live", created_at: "2026-03-02", updated_at: "2026-03-10"
  },
  {
    id: "l18", product_id: "p18", title: "Basket Air Fryer 6L", description: "Large 6L basket air fryer with adjustable temperature, 60-minute timer, and non-stick basket. Fry, bake, roast and grill with little to no oil. Family-sized portions.", category: "Home & Kitchen", slug: "basket-air-fryer-6l", images: ["https://media.takealot.com/covers_images/055772c8fe06464e8258d4af33a67132/s-zoom.file", "https://media.takealot.com/covers_images/055772c8fe06464e8258d4af33a67132/s-fb.file"], current_price: 749, original_price: 1199, sku: "SB-FRY002", stock_quantity: 22, is_in_stock: true, rating_average: 4.5, rating_count: 3193, tags: ["air-fryer", "kitchen", "healthy-cooking", "6-litre"], attributes: { "Capacity": "6L", "Timer": "60 min", "Power": "1500W" }, brand: "ShopMO", status: "live", created_at: "2026-03-01", updated_at: "2026-03-13"
  },
  {
    id: "l19", product_id: "p19", title: "XXL Digital Air Fryer with Tongs Set", description: "Extra-large digital air fryer with LED display, 8 preset programs, and bonus silicone tongs set. Non-stick removable basket. Perfect for family meals and entertaining.", category: "Home & Kitchen", slug: "xxl-digital-air-fryer-tongs-set", images: ["https://media.takealot.com/covers_images/281cb5b990374d3992b71f4b67a87f16/s-zoom.file", "https://media.takealot.com/covers_images/281cb5b990374d3992b71f4b67a87f16/s-fb.file"], current_price: 849, original_price: 1299, sku: "SB-FRY003", stock_quantity: 16, is_in_stock: true, rating_average: 4.6, rating_count: 2135, tags: ["air-fryer", "xxl", "digital", "kitchen"], attributes: { "Size": "XXL", "Programs": "8 presets", "Bonus": "Tongs Set" }, brand: "ShopMO", status: "live", created_at: "2026-03-05", updated_at: "2026-03-14"
  },
  {
    id: "l20", product_id: "p20", title: "Cooking Utensil Set 11 Piece with Holder", description: "Complete 11-piece silicone cooking utensil set with stylish holder. Heat-resistant, non-scratch, BPA-free. Includes spatula, ladle, tongs, whisk, and more.", category: "Home & Kitchen", slug: "cooking-utensil-set-11-piece-holder", images: ["https://media.takealot.com/covers_images/acce524957ca46898b4377bdfb19abf2/s-zoom.file", "https://media.takealot.com/covers_images/acce524957ca46898b4377bdfb19abf2/s-fb.file"], current_price: 162, original_price: 249, sku: "SB-UTN001", stock_quantity: 50, is_in_stock: true, rating_average: 4.7, rating_count: 2188, tags: ["utensils", "kitchen", "cooking", "silicone"], attributes: { "Pieces": "11", "Material": "Silicone + Wood", "Heat Resistant": "230C" }, brand: "ShopMO", status: "live", created_at: "2026-03-06", updated_at: "2026-03-14"
  },
  {
    id: "l21", product_id: "p21", title: "5M RGB LED Strip Light", description: "5 metres RGB LED strip light with remote control. 16 colours, multiple lighting modes, self-adhesive backing. Transform any room instantly. Easy DIY installation.", category: "Home & Kitchen", slug: "5m-rgb-led-strip-light", images: ["https://media.takealot.com/covers_images/83713d946aad465aac061a7f9de882aa/s-zoom.file", "https://media.takealot.com/covers_images/83713d946aad465aac061a7f9de882aa/s-fb.file"], current_price: 199, original_price: 299, sku: "SB-LED001", stock_quantity: 75, is_in_stock: true, rating_average: 3.8, rating_count: 3812, tags: ["led", "strip-light", "rgb", "room-decor"], attributes: { "Length": "5M", "Colours": "16 RGB", "Remote": "Included" }, brand: "ShopMO", status: "live", created_at: "2026-03-03", updated_at: "2026-03-11"
  },
  {
    id: "l22", product_id: "p22", title: "Solar Home Lighting System 3 LED Bulbs", description: "Off-grid solar lighting system with solar panel, 3 LED bulbs, and rechargeable battery. USB charging port for phone. Essential for load shedding preparedness.", category: "Electronics", slug: "solar-home-lighting-system-3-led-bulbs", images: ["https://media.takealot.com/covers_images/eb88e5fbd7d74f3b9b4990381e72c198/s-zoom.file", "https://media.takealot.com/covers_images/eb88e5fbd7d74f3b9b4990381e72c198/s-fb.file"], current_price: 429, original_price: 649, sku: "SB-SOL001", stock_quantity: 20, is_in_stock: true, rating_average: 4.3, rating_count: 119, tags: ["solar", "load-shedding", "lighting", "off-grid"], attributes: { "Bulbs": "3 LED", "Panel": "Solar", "USB Charging": "Yes" }, brand: "ShopMO", status: "live", created_at: "2026-03-04", updated_at: "2026-03-12"
  },
  {
    id: "l23", product_id: "p23", title: "Fitness Stepper with Resistance Bands", description: "Compact mini stepper with adjustable resistance bands for full-body workout. LCD display tracks steps, time, and calories. Perfect home gym equipment.", category: "Sports & Outdoors", slug: "fitness-stepper-resistance-bands", images: ["https://media.takealot.com/covers_images/e4eebad25fe041d3b460ea24aeea874c/s-zoom.file", "https://media.takealot.com/covers_images/e4eebad25fe041d3b460ea24aeea874c/s-fb.file"], current_price: 499, original_price: 749, sku: "SB-STP001", stock_quantity: 15, is_in_stock: true, rating_average: 4.2, rating_count: 902, tags: ["stepper", "fitness", "home-gym", "resistance-bands"], attributes: { "Display": "LCD", "Bands": "Included", "Max Weight": "100kg" }, brand: "ShopMO", status: "live", created_at: "2026-03-07", updated_at: "2026-03-14"
  },
  {
    id: "l24", product_id: "p24", title: "20W Solar Charger Portable Waterproof", description: "Foldable 20W solar charger with dual USB ports. Waterproof and portable for hiking, camping, and outdoor adventures. Charges phones and tablets directly from the sun.", category: "Sports & Outdoors", slug: "20w-solar-charger-portable-waterproof", images: ["https://media.takealot.com/covers_images/6f6144bdf8ce406d94dd1f0ab3f6d7cb/s-zoom.file", "https://media.takealot.com/covers_images/6f6144bdf8ce406d94dd1f0ab3f6d7cb/s-fb.file"], current_price: 365, original_price: 549, sku: "SB-SLR002", stock_quantity: 28, is_in_stock: true, rating_average: 4.3, rating_count: 162, tags: ["solar-charger", "portable", "waterproof", "outdoor"], attributes: { "Power": "20W", "Ports": "Dual USB", "Waterproof": "Yes" }, brand: "ShopMO", status: "live", created_at: "2026-03-05", updated_at: "2026-03-13"
  },
  {
    id: "l25", product_id: "p25", title: "TAPO L900-5 Smart WiFi Light Strip 5m", description: "TP-Link TAPO smart WiFi LED light strip. Works with Alexa and Google Home. 16 million colours, music sync, and schedule via app. No hub required.", category: "Electronics", slug: "tapo-l900-5-smart-wifi-light-strip-5m", images: ["https://media.takealot.com/covers_images/ad19f12f191f49909c8cef20e9fa7337/s-zoom.file", "https://media.takealot.com/covers_images/ad19f12f191f49909c8cef20e9fa7337/s-fb.file"], current_price: 369, original_price: 549, sku: "SB-TPO001", stock_quantity: 35, is_in_stock: true, rating_average: 4.9, rating_count: 50, tags: ["smart-light", "wifi", "led-strip", "alexa"], attributes: { "Length": "5M", "Colours": "16 million", "Voice Control": "Alexa & Google" }, brand: "ShopMO", status: "live", created_at: "2026-03-08", updated_at: "2026-03-14"
  },
  {
    id: "l26", product_id: "p26", title: "Under Cabinet Lights Motion Sensor 2-Pack", description: "Rechargeable LED under cabinet lights with motion sensor, 2-pack. Magnetic strip installation, 3 colour temperatures. Perfect for kitchen, wardrobe, or hallway.", category: "Home & Kitchen", slug: "under-cabinet-lights-motion-sensor-2-pack", images: ["https://media.takealot.com/covers_images/7fc84050ba4d4ccba652968de91465c6/s-zoom.file", "https://media.takealot.com/covers_images/7fc84050ba4d4ccba652968de91465c6/s-fb.file"], current_price: 397, original_price: 599, sku: "SB-CAB001", stock_quantity: 32, is_in_stock: true, rating_average: 4.6, rating_count: 91, tags: ["cabinet-light", "motion-sensor", "led", "rechargeable"], attributes: { "Pack": "2 lights", "Sensor": "Motion", "Install": "Magnetic" }, brand: "ShopMO", status: "live", created_at: "2026-03-06", updated_at: "2026-03-13"
  },
  {
    id: "l27", product_id: "p27", title: "Triple Lens Dash Camera with Parking Mode", description: "3-channel dash camera covering front, cabin, and rear. Parking mode with motion detection, loop recording, and night vision. Stay safe on South African roads.", category: "Automotive", slug: "triple-lens-dash-camera-parking-mode", images: ["https://media.takealot.com/covers_images/e20985b203104d2bb93b1c1efdf5bdc3/s-zoom.file", "https://media.takealot.com/covers_images/e20985b203104d2bb93b1c1efdf5bdc3/s-fb.file"], current_price: 277, original_price: 449, sku: "SB-DSH002", stock_quantity: 24, is_in_stock: true, rating_average: 3.9, rating_count: 110, tags: ["dash-cam", "triple-lens", "parking-mode", "car-safety"], attributes: { "Lenses": "3 (Front/Cabin/Rear)", "Parking Mode": "Yes", "Night Vision": "Yes" }, brand: "ShopMO", status: "live", created_at: "2026-03-07", updated_at: "2026-03-14"
  },
  {
    id: "l28", product_id: "p28", title: "Silicone Kitchen Utensil Set 19 Pieces", description: "Complete 19-piece premium silicone kitchen utensil set with wooden handles and holder. Heat-resistant up to 230C, non-stick safe, and dishwasher friendly.", category: "Home & Kitchen", slug: "silicone-kitchen-utensil-set-19-pieces", images: ["https://media.takealot.com/covers_images/9c30513cfdc848dc9ac35e06b26c483a/s-zoom.file", "https://media.takealot.com/covers_images/9c30513cfdc848dc9ac35e06b26c483a/s-fb.file"], current_price: 227, original_price: 349, sku: "SB-UTN002", stock_quantity: 38, is_in_stock: true, rating_average: 4.0, rating_count: 964, tags: ["utensils", "kitchen", "silicone", "19-piece"], attributes: { "Pieces": "19", "Material": "Silicone + Wood", "Heat Resistant": "230C" }, brand: "ShopMO", status: "live", created_at: "2026-03-04", updated_at: "2026-03-12"
  },
  {
    id: "l29", product_id: "p29", title: "Tabletop Drum Grater Shredder", description: "Manual rotary drum grater and shredder with 3 interchangeable stainless steel drums. Grate cheese, vegetables, and nuts quickly. Suction base for stability.", category: "Home & Kitchen", slug: "tabletop-drum-grater-shredder", images: ["https://media.takealot.com/covers_images/12d46ff6c9ed49a19bc11f6fe1928e08/s-zoom.file", "https://media.takealot.com/covers_images/12d46ff6c9ed49a19bc11f6fe1928e08/s-fb.file"], current_price: 193, original_price: 299, sku: "SB-GRT001", stock_quantity: 42, is_in_stock: true, rating_average: 4.1, rating_count: 253, tags: ["grater", "kitchen", "shredder", "manual"], attributes: { "Drums": "3 interchangeable", "Material": "Stainless Steel", "Base": "Suction" }, brand: "ShopMO", status: "live", created_at: "2026-03-05", updated_at: "2026-03-13"
  },
  {
    id: "l30", product_id: "p30", title: "20M WiFi LED Strip Light Alexa Compatible", description: "20 metres WiFi LED strip light compatible with Alexa and Google Assistant. App control, music sync, timer, and 16 million colours. Cover an entire room.", category: "Electronics", slug: "20m-wifi-led-strip-light-alexa-compatible", images: ["https://media.takealot.com/covers_images/9052fbb755d14139868b20411b97d6d4/s-zoom.file", "https://media.takealot.com/covers_images/9052fbb755d14139868b20411b97d6d4/s-fb.file"], current_price: 259, original_price: 399, sku: "SB-LED002", stock_quantity: 45, is_in_stock: true, rating_average: 4.3, rating_count: 91, tags: ["led-strip", "wifi", "alexa", "smart-home"], attributes: { "Length": "20M", "Voice Control": "Alexa & Google", "Colours": "16 million" }, brand: "ShopMO", status: "live", created_at: "2026-03-08", updated_at: "2026-03-14"
  },
  {
    id: "l31", product_id: "p31", title: "Exercise Loop Bands 5-piece Set", description: "Set of 5 premium latex exercise loop bands with varying resistance levels. Ideal for glutes, legs, physio, and warm-ups. Includes carry bag.", category: "Sports & Outdoors", slug: "exercise-loop-bands-5-piece-set", images: ["https://media.takealot.com/covers_images/5d9284da1d7f4f80b29c958cdd552a46/s-zoom.file", "https://media.takealot.com/covers_images/5d9284da1d7f4f80b29c958cdd552a46/s-fb.file"], current_price: 159, original_price: 249, sku: "SB-LPB001", stock_quantity: 55, is_in_stock: true, rating_average: 4.4, rating_count: 210, tags: ["loop-bands", "fitness", "exercise", "glutes"], attributes: { "Bands": "5 levels", "Material": "Natural Latex", "Bag": "Included" }, brand: "ShopMO", status: "live", created_at: "2026-03-06", updated_at: "2026-03-13"
  },
  {
    id: "l32", product_id: "p32", title: "Soundcore A20i True Wireless Earbuds", description: "Anker Soundcore A20i with custom EQ, 28-hour total playtime, Bluetooth 5.3, and AI-enhanced calls. Ultra-lightweight and comfortable. App customisable.", category: "Electronics", slug: "soundcore-a20i-true-wireless-earbuds", images: ["https://media.takealot.com/covers_images/faba1773776b4e6b8766ae9a4e8b6d00/s-zoom.file", "https://media.takealot.com/covers_images/faba1773776b4e6b8766ae9a4e8b6d00/s-fb.file"], current_price: 299, original_price: 449, sku: "SB-SNC002", stock_quantity: 33, is_in_stock: true, rating_average: 4.6, rating_count: 630, tags: ["earbuds", "wireless", "soundcore", "bluetooth"], attributes: { "Bluetooth": "5.3", "Battery": "28 hours", "AI Calls": "Yes" }, brand: "ShopMO", status: "live", created_at: "2026-03-09", updated_at: "2026-03-15"
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: "d1", listing_id: "l7", deal_type: "flash_sale", original_price: 1599, deal_price: 999, discount_percentage: 38, quantity_available: 10, quantity_sold: 7, starts_at: new Date(Date.now() - 3600000).toISOString(), ends_at: new Date(Date.now() + 86400000).toISOString(), is_active: true, priority: 1, created_at: "", listing: MOCK_LISTINGS[6]
  },
  {
    id: "d2", listing_id: "l2", deal_type: "flash_sale", original_price: 499, deal_price: 299, discount_percentage: 40, quantity_available: 35, quantity_sold: 18, starts_at: new Date(Date.now() - 7200000).toISOString(), ends_at: new Date(Date.now() + 43200000).toISOString(), is_active: true, priority: 2, created_at: "", listing: MOCK_LISTINGS[1]
  },
  {
    id: "d3", listing_id: "l5", deal_type: "daily_deal", original_price: 449, deal_price: 279, discount_percentage: 38, quantity_available: 40, quantity_sold: 12, starts_at: new Date(Date.now() - 14400000).toISOString(), ends_at: new Date(Date.now() + 72000000).toISOString(), is_active: true, priority: 3, created_at: "", listing: MOCK_LISTINGS[4]
  },
  {
    id: "d4", listing_id: "l18", deal_type: "flash_sale", original_price: 1199, deal_price: 749, discount_percentage: 38, quantity_available: 22, quantity_sold: 14, starts_at: new Date(Date.now() - 5400000).toISOString(), ends_at: new Date(Date.now() + 64800000).toISOString(), is_active: true, priority: 4, created_at: "", listing: MOCK_LISTINGS[17]
  },
  {
    id: "d5", listing_id: "l15", deal_type: "daily_deal", original_price: 249, deal_price: 159, discount_percentage: 36, quantity_available: 65, quantity_sold: 29, starts_at: new Date(Date.now() - 10800000).toISOString(), ends_at: new Date(Date.now() + 54000000).toISOString(), is_active: true, priority: 5, created_at: "", listing: MOCK_LISTINGS[14]
  },
];

export const MOCK_REVIEWS: CustomerReview[] = [
  // Fast Charger reviews
  { id: "r1", customer_id: "c1", listing_id: "l1", customer_order_id: "o1", rating: 5, title: "Excellent charger!", body: "Charges my Samsung S24 super fast. Great value for money. Cable quality is also very good.", images: [], is_verified_purchase: true, helpful_count: 12, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Thabo M.", avatar_url: null } },
  { id: "r2", customer_id: "c2", listing_id: "l1", customer_order_id: "o2", rating: 4, title: "Good quality", body: "Works well, charges quickly. The cable could be a bit longer though.", images: [], is_verified_purchase: true, helpful_count: 5, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-08", updated_at: "2026-03-08", customer: { full_name: "Naledi K.", avatar_url: null } },
  { id: "r1b", customer_id: "c20", listing_id: "l1", customer_order_id: "o20", rating: 5, title: "Best charger I've owned", body: "Bought this for my Huawei and it charges from 10% to 100% in about an hour. The braided cable is solid quality. Already ordered a second one for the office.", images: [], is_verified_purchase: true, helpful_count: 8, status: "approved", seller_response: "Thank you for the support! Enjoy fast charging!", seller_responded_at: "2026-03-09", created_at: "2026-03-07", updated_at: "2026-03-09", customer: { full_name: "Andile Z.", avatar_url: null } },
  // Wireless Earbuds reviews
  { id: "r4", customer_id: "c4", listing_id: "l2", customer_order_id: "o4", rating: 5, title: "Better than AirPods!", body: "The noise cancellation is incredible. I use these daily on my taxi commute and they block out everything. Battery lasts all week. Best purchase this year.", images: [], is_verified_purchase: true, helpful_count: 34, status: "approved", seller_response: "We're so glad you love them! The ANC is top-tier indeed.", seller_responded_at: "2026-03-06", created_at: "2026-03-05", updated_at: "2026-03-06", customer: { full_name: "Zinhle D.", avatar_url: null } },
  { id: "r5", customer_id: "c5", listing_id: "l2", customer_order_id: "o5", rating: 5, title: "Amazing sound quality", body: "Deep bass and crystal clear vocals. The fit is comfortable even for long gym sessions. Definitely worth the money.", images: [], is_verified_purchase: true, helpful_count: 19, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-02", updated_at: "2026-03-02", customer: { full_name: "Bongani S.", avatar_url: null } },
  { id: "r5b", customer_id: "c21", listing_id: "l2", customer_order_id: "o21", rating: 4, title: "Great for the price", body: "Sound quality is really good for this price range. Only downside is the case is a bit bulky. But overall very happy with my purchase.", images: [], is_verified_purchase: true, helpful_count: 7, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-02-28", updated_at: "2026-02-28", customer: { full_name: "Lerato M.", avatar_url: null } },
  // Smart Watch reviews
  { id: "r6", customer_id: "c6", listing_id: "l3", customer_order_id: "o6", rating: 5, title: "Love this watch!", body: "The fitness tracking is accurate and the display is gorgeous. Battery lasts a full week. I get compliments on it everywhere I go.", images: [], is_verified_purchase: true, helpful_count: 22, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Karabo P.", avatar_url: null } },
  { id: "r7", customer_id: "c7", listing_id: "l3", customer_order_id: "o7", rating: 4, title: "Great fitness companion", body: "Tracks my runs and gym sessions perfectly. The heart rate monitor is spot-on compared to my gym's machines. The app could be better though.", images: [], is_verified_purchase: true, helpful_count: 15, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-04", updated_at: "2026-03-04", customer: { full_name: "Mandla K.", avatar_url: null } },
  // Bluetooth Speaker reviews
  { id: "r8", customer_id: "c8", listing_id: "l4", customer_order_id: "o8", rating: 5, title: "Perfect for braais!", body: "This speaker is LOUD. Used it at our braai last weekend and everyone was impressed. Sound quality is amazing for the price. Waterproof too which is a bonus by the pool.", images: [], is_verified_purchase: true, helpful_count: 41, status: "approved", seller_response: "Thank you! Nothing like good music at a braai! 🔥", seller_responded_at: "2026-03-08", created_at: "2026-03-07", updated_at: "2026-03-08", customer: { full_name: "Sizwe N.", avatar_url: null } },
  { id: "r9", customer_id: "c9", listing_id: "l4", customer_order_id: "o9", rating: 5, title: "Best speaker under R500", body: "Deep bass, loud volume, and the battery lasts all day. I've had it for a month and no issues. Highly recommend.", images: [], is_verified_purchase: true, helpful_count: 27, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-01", updated_at: "2026-03-01", customer: { full_name: "Ayanda T.", avatar_url: null } },
  // Ring Light reviews
  { id: "r10", customer_id: "c10", listing_id: "l5", customer_order_id: "o10", rating: 5, title: "TikTok game changer!", body: "My content looks so much more professional now. The lighting is adjustable and the tripod is sturdy. Already gained more followers since using this!", images: [], is_verified_purchase: true, helpful_count: 56, status: "approved", seller_response: "We love supporting content creators! Keep shining! ✨", seller_responded_at: "2026-03-04", created_at: "2026-03-03", updated_at: "2026-03-04", customer: { full_name: "Palesa M.", avatar_url: null } },
  // Air Fryer reviews
  { id: "r3", customer_id: "c3", listing_id: "l7", customer_order_id: "o3", rating: 5, title: "Best air fryer!", body: "This air fryer is amazing! Made the best chips and chicken wings. So much healthier than deep frying. The digital display is easy to use.", images: [], is_verified_purchase: true, helpful_count: 28, status: "approved", seller_response: "Thank you for the wonderful review! Enjoy your healthy meals!", seller_responded_at: "2026-03-12", created_at: "2026-03-11", updated_at: "2026-03-12", customer: { full_name: "Sipho N.", avatar_url: null } },
  { id: "r11", customer_id: "c11", listing_id: "l7", customer_order_id: "o11", rating: 5, title: "Life changing appliance", body: "I cook everything in this now — from wings to vetkoek! The 5.5L size is perfect for a family of 4. Uses almost no oil and everything comes out crispy.", images: [], is_verified_purchase: true, helpful_count: 45, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-08", updated_at: "2026-03-08", customer: { full_name: "Nomsa G.", avatar_url: null } },
  { id: "r12", customer_id: "c12", listing_id: "l7", customer_order_id: "o12", rating: 4, title: "Great value for money", body: "Works well for the price. The 8 presets cover most of what I need. Only wish it was a bit quieter. But the food comes out perfectly every time.", images: [], is_verified_purchase: true, helpful_count: 18, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-05", updated_at: "2026-03-05", customer: { full_name: "Tshepo R.", avatar_url: null } },
  // Yoga Mat reviews
  { id: "r13", customer_id: "c13", listing_id: "l8", customer_order_id: "o13", rating: 5, title: "Non-slip and comfortable", body: "Finally a mat that doesn't slide around during downward dog! The alignment lines are super helpful for beginners like me. Great quality for the price.", images: [], is_verified_purchase: true, helpful_count: 14, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Busisiwe L.", avatar_url: null } },
  // Resistance Bands reviews
  { id: "r14", customer_id: "c14", listing_id: "l9", customer_order_id: "o14", rating: 5, title: "Perfect home gym addition", body: "These bands are excellent quality — no snapping like cheap ones I've had before. The 5 different resistance levels give me a full workout at home. Saved me a gym membership!", images: [], is_verified_purchase: true, helpful_count: 31, status: "approved", seller_response: "Glad we could help with your fitness journey! 💪", seller_responded_at: "2026-03-06", created_at: "2026-03-05", updated_at: "2026-03-06", customer: { full_name: "Dumisani V.", avatar_url: null } },
  // Water Bottle reviews
  { id: "r15", customer_id: "c15", listing_id: "l10", customer_order_id: "o15", rating: 5, title: "Keeps water ice cold!", body: "Put ice water in at 6am, still cold at 5pm. This bottle is unreal. No condensation on the outside either. Taking it everywhere.", images: [], is_verified_purchase: true, helpful_count: 23, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Mpho B.", avatar_url: null } },
  // Vitamin C Serum reviews
  { id: "r16", customer_id: "c16", listing_id: "l11", customer_order_id: "o16", rating: 5, title: "My skin is glowing!", body: "After 2 weeks of using this serum my dark spots have faded noticeably. My skin feels hydrated and looks brighter. Friends keep asking what I'm using!", images: [], is_verified_purchase: true, helpful_count: 38, status: "approved", seller_response: "Beautiful skin for a beautiful person! Thank you! ✨", seller_responded_at: "2026-03-11", created_at: "2026-03-10", updated_at: "2026-03-11", customer: { full_name: "Nandi J.", avatar_url: null } },
  { id: "r17", customer_id: "c17", listing_id: "l11", customer_order_id: "o17", rating: 4, title: "Effective and affordable", body: "Really good serum for the price. Absorbs quickly, not oily. I've tried expensive brands and this is just as good. Will definitely repurchase.", images: [], is_verified_purchase: true, helpful_count: 16, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-06", updated_at: "2026-03-06", customer: { full_name: "Zanele W.", avatar_url: null } },
  // Car Phone Mount reviews
  { id: "r18", customer_id: "c18", listing_id: "l12", customer_order_id: "o18", rating: 4, title: "Strong magnet", body: "Holds my iPhone firmly even on Joburg potholes! Easy to install, no tools needed. The 360 rotation is smooth. Good buy.", images: [], is_verified_purchase: true, helpful_count: 11, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Lebo F.", avatar_url: null } },
  { id: "r19", customer_id: "c19", listing_id: "l12", customer_order_id: "o19", rating: 5, title: "Works perfectly", body: "Simple, effective, and looks sleek on my dashboard. My phone stays in place even in speed bumps. Perfect for using Google Maps on long trips.", images: [], is_verified_purchase: true, helpful_count: 9, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-04", updated_at: "2026-03-04", customer: { full_name: "Andile P.", avatar_url: null } },
  // Volkano Scorpio Earphones reviews
  { id: "r20", customer_id: "c22", listing_id: "l13", customer_order_id: "o22", rating: 5, title: "Perfect for my taxi commute", body: "These earphones block out taxi noise perfectly. Sound is crisp, bass is solid, and the case is compact enough for my pocket. Battery lasts me the whole week.", images: [], is_verified_purchase: true, helpful_count: 19, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Thabo N.", avatar_url: null } },
  { id: "r21", customer_id: "c23", listing_id: "l13", customer_order_id: "o23", rating: 4, title: "Great value for under R400", body: "Bought these for gym and daily use. Sound quality surprised me for the price. Touch controls take a bit of getting used to but overall very happy.", images: [], is_verified_purchase: true, helpful_count: 11, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-08", updated_at: "2026-03-08", customer: { full_name: "Naledi S.", avatar_url: null } },
  // soundcore R50i reviews
  { id: "r22", customer_id: "c24", listing_id: "l14", customer_order_id: "o24", rating: 5, title: "Best earbuds I've owned", body: "The app EQ customisation is amazing. Bass boost mode is perfect for amapiano. Battery life is unreal - I charge once a week. Worth every cent.", images: [], is_verified_purchase: true, helpful_count: 25, status: "approved", seller_response: "Thank you! The soundcore app really takes the experience to the next level!", seller_responded_at: "2026-03-13", created_at: "2026-03-12", updated_at: "2026-03-13", customer: { full_name: "Sipho K.", avatar_url: null } },
  { id: "r23", customer_id: "c25", listing_id: "l14", customer_order_id: "o25", rating: 5, title: "Incredible sound for the price", body: "Coming from expensive Sony earbuds, these Anker ones hold their own. Comfortable fit, great sound stage, and the IPX5 means I don't stress at gym.", images: [], is_verified_purchase: true, helpful_count: 14, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Lerato D.", avatar_url: null } },
  // WINX GO Power Bank reviews
  { id: "r24", customer_id: "c26", listing_id: "l15", customer_order_id: "o26", rating: 5, title: "Load shedding lifesaver!", body: "This power bank is essential for load shedding. Charges my phone twice over and it's slim enough to carry in my bag every day. Charges fast too.", images: [], is_verified_purchase: true, helpful_count: 32, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-11", updated_at: "2026-03-11", customer: { full_name: "Karabo M.", avatar_url: null } },
  { id: "r25", customer_id: "c27", listing_id: "l15", customer_order_id: "o27", rating: 4, title: "Compact and reliable", body: "Been using it for 2 weeks now. Perfect size, charges my Samsung S23 about 2.5 times. LED indicator is useful. Only wish it had USB-C output.", images: [], is_verified_purchase: true, helpful_count: 8, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-07", updated_at: "2026-03-07", customer: { full_name: "Mpho T.", avatar_url: null } },
  // 40000mAh Power Bank reviews
  { id: "r26", customer_id: "c28", listing_id: "l16", customer_order_id: "o28", rating: 5, title: "Monster battery for load shedding", body: "This thing is a beast. Charged my phone 8 times, my wife's phone 5 times, and still had juice left. The fast charging is legit. Heavy but worth it.", images: [], is_verified_purchase: true, helpful_count: 22, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Bongani L.", avatar_url: null } },
  // 4K Dash Cam reviews
  { id: "r27", customer_id: "c29", listing_id: "l17", customer_order_id: "o29", rating: 5, title: "Crystal clear footage", body: "Video quality is amazing, even at night. Already captured a near-miss on the N1. The 64GB card means I don't need to worry about storage. Essential for Joburg driving.", images: [], is_verified_purchase: true, helpful_count: 17, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Zinhle M.", avatar_url: null } },
  { id: "r28", customer_id: "c30", listing_id: "l17", customer_order_id: "o30", rating: 4, title: "Good cam, easy setup", body: "Installed in 10 minutes. Picture quality is excellent during the day. Night vision is decent but not perfect. For the price, it's a solid buy.", images: [], is_verified_purchase: true, helpful_count: 6, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-06", updated_at: "2026-03-06", customer: { full_name: "Andile R.", avatar_url: null } },
  // Basket Air Fryer 6L reviews
  { id: "r29", customer_id: "c31", listing_id: "l18", customer_order_id: "o31", rating: 5, title: "Best kitchen purchase ever", body: "This 6L air fryer feeds my family of 5 easily. Made pap chips, chicken wings, and even baked a cake. Uses barely any oil. Eskom can keep their electricity - we braai everything in this!", images: [], is_verified_purchase: true, helpful_count: 45, status: "approved", seller_response: "We love that you're getting creative with it! Enjoy!", seller_responded_at: "2026-03-13", created_at: "2026-03-12", updated_at: "2026-03-13", customer: { full_name: "Dumisani N.", avatar_url: null } },
  { id: "r30", customer_id: "c32", listing_id: "l18", customer_order_id: "o32", rating: 4, title: "Great size for families", body: "Big enough for a whole chicken. Easy to clean, cooks evenly. Timer is a nice touch. Only 4 stars because the manual could be better - had to YouTube how to use it.", images: [], is_verified_purchase: true, helpful_count: 13, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-08", updated_at: "2026-03-08", customer: { full_name: "Busisiwe K.", avatar_url: null } },
  // XXL Digital Air Fryer reviews
  { id: "r31", customer_id: "c33", listing_id: "l19", customer_order_id: "o33", rating: 5, title: "Replaced my oven completely", body: "Haven't used my oven since getting this. The digital presets make everything easy. The free tongs are quality too. Made the best boerewors rolls in this thing.", images: [], is_verified_purchase: true, helpful_count: 28, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-11", updated_at: "2026-03-11", customer: { full_name: "Tshepo M.", avatar_url: null } },
  // Cooking Utensil Set reviews
  { id: "r32", customer_id: "c34", listing_id: "l20", customer_order_id: "o34", rating: 5, title: "Beautiful and practical", body: "The holder looks amazing on my kitchen counter. Utensils are sturdy and don't scratch my pots. Heat resistant - tested it myself. Great gift idea too.", images: [], is_verified_purchase: true, helpful_count: 16, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Nandi P.", avatar_url: null } },
  { id: "r33", customer_id: "c35", listing_id: "l20", customer_order_id: "o35", rating: 5, title: "Complete set, great value", body: "Everything you need in one box. The wooden handles feel premium and the silicone doesn't stain. Bought one for myself and one for my sister.", images: [], is_verified_purchase: true, helpful_count: 10, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-07", updated_at: "2026-03-07", customer: { full_name: "Zanele V.", avatar_url: null } },
  // 5M RGB LED Strip Light reviews
  { id: "r34", customer_id: "c36", listing_id: "l21", customer_order_id: "o36", rating: 4, title: "Room looks amazing now", body: "Put these behind my TV and around my desk. The remote is handy. Adhesive could be stronger though - used extra tape on some corners. But the vibe is 10/10.", images: [], is_verified_purchase: true, helpful_count: 21, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Ayanda S.", avatar_url: null } },
  // Solar Home Lighting System reviews
  { id: "r35", customer_id: "c37", listing_id: "l22", customer_order_id: "o37", rating: 4, title: "Essential for load shedding", body: "These solar lights are a game-changer during load shedding. Three bulbs light up the lounge, kitchen, and bathroom. Phone charging port is a bonus. Takes a full day to charge in Pretoria sun.", images: [], is_verified_purchase: true, helpful_count: 33, status: "approved", seller_response: "Glad it's helping during load shedding! Solar is the way forward.", seller_responded_at: "2026-03-12", created_at: "2026-03-11", updated_at: "2026-03-12", customer: { full_name: "Nomsa B.", avatar_url: null } },
  { id: "r36", customer_id: "c38", listing_id: "l22", customer_order_id: "o38", rating: 4, title: "Decent backup lighting", body: "Bought this for my gogo in the rural areas. Works well, bulbs are bright enough. USB charging for phones is very useful. Good value for what you get.", images: [], is_verified_purchase: true, helpful_count: 15, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-08", updated_at: "2026-03-08", customer: { full_name: "Lebo K.", avatar_url: null } },
  // Fitness Stepper reviews
  { id: "r37", customer_id: "c39", listing_id: "l23", customer_order_id: "o39", rating: 4, title: "Great home workout", body: "Compact enough for my flat in Joburg. The resistance bands add upper body work to the stepping. LCD counter motivates me. Bit squeaky at first but settled after a week.", images: [], is_verified_purchase: true, helpful_count: 12, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-12", updated_at: "2026-03-12", customer: { full_name: "Palesa G.", avatar_url: null } },
  // 20W Solar Charger reviews
  { id: "r38", customer_id: "c40", listing_id: "l24", customer_order_id: "o40", rating: 5, title: "Camping essential", body: "Took this to Kruger National Park and it kept both our phones charged the entire trip. Folds flat, super lightweight. Charged my phone fully in about 3 hours of direct sun.", images: [], is_verified_purchase: true, helpful_count: 18, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Sipho D.", avatar_url: null } },
  // TAPO Smart Light Strip reviews
  { id: "r39", customer_id: "c41", listing_id: "l25", customer_order_id: "o41", rating: 5, title: "Smart home dream", body: "Setup was easy through the TAPO app. Voice control with Alexa is brilliant. The music sync feature is incredible for house parties. Colours are vivid and bright.", images: [], is_verified_purchase: true, helpful_count: 9, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-13", updated_at: "2026-03-13", customer: { full_name: "Karabo S.", avatar_url: null } },
  // Under Cabinet Lights reviews
  { id: "r40", customer_id: "c42", listing_id: "l26", customer_order_id: "o42", rating: 5, title: "Kitchen game changer", body: "Installed under my kitchen cabinets in 5 minutes. The motion sensor means no more fumbling for switches. Light is bright and warm. Rechargeable so no wiring needed.", images: [], is_verified_purchase: true, helpful_count: 7, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-11", updated_at: "2026-03-11", customer: { full_name: "Zinhle T.", avatar_url: null } },
  // Triple Lens Dash Camera reviews
  { id: "r41", customer_id: "c43", listing_id: "l27", customer_order_id: "o43", rating: 4, title: "Three cameras for this price", body: "The front cam is decent quality, cabin cam is useful for Uber drivers, and rear cam helps with parking. Night quality could be better but for R277 you can't complain.", images: [], is_verified_purchase: true, helpful_count: 14, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Andile M.", avatar_url: null } },
  // Silicone Kitchen Utensil Set 19 Pieces reviews
  { id: "r42", customer_id: "c44", listing_id: "l28", customer_order_id: "o44", rating: 4, title: "Comprehensive set", body: "19 pieces covers everything you'll ever need. Quality is good for the price. Wooden handles look classy. A few pieces feel a bit thin but most are solid.", images: [], is_verified_purchase: true, helpful_count: 8, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-09", updated_at: "2026-03-09", customer: { full_name: "Mpho N.", avatar_url: null } },
  // Tabletop Drum Grater reviews
  { id: "r43", customer_id: "c45", listing_id: "l29", customer_order_id: "o45", rating: 4, title: "Makes grating so easy", body: "Grated a block of cheddar in seconds. The suction base keeps it stable. Three different drums for different textures. My kids love helping with it now. Easy to clean too.", images: [], is_verified_purchase: true, helpful_count: 11, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-11", updated_at: "2026-03-11", customer: { full_name: "Busisiwe M.", avatar_url: null } },
  // 20M WiFi LED Strip Light reviews
  { id: "r44", customer_id: "c46", listing_id: "l30", customer_order_id: "o46", rating: 4, title: "20 metres covers my whole room", body: "Did my entire bedroom ceiling perimeter and still had strip left over. App control is convenient. Music sync works well for setting the mood. Great value.", images: [], is_verified_purchase: true, helpful_count: 13, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-12", updated_at: "2026-03-12", customer: { full_name: "Tshepo L.", avatar_url: null } },
  // Exercise Loop Bands reviews
  { id: "r45", customer_id: "c47", listing_id: "l31", customer_order_id: "o47", rating: 5, title: "Perfect for glute workouts", body: "These loop bands are exactly what I needed for my home glute workout routine. Five different resistances so I can progress. Much better quality than the cheap ones from the market.", images: [], is_verified_purchase: true, helpful_count: 16, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-13", updated_at: "2026-03-13", customer: { full_name: "Lerato P.", avatar_url: null } },
  // Soundcore A20i reviews
  { id: "r46", customer_id: "c48", listing_id: "l32", customer_order_id: "o48", rating: 5, title: "Incredible for R299", body: "Bluetooth 5.3 connection is rock solid. Call quality with the AI feature is surprisingly good. Comfortable enough to wear all day at the office. App EQ is a nice bonus.", images: [], is_verified_purchase: true, helpful_count: 20, status: "approved", seller_response: "Thank you! The A20i really punches above its weight class!", seller_responded_at: "2026-03-15", created_at: "2026-03-14", updated_at: "2026-03-15", customer: { full_name: "Dumisani K.", avatar_url: null } },
  { id: "r47", customer_id: "c49", listing_id: "l32", customer_order_id: "o49", rating: 4, title: "Solid budget earbuds", body: "For under R300 these are excellent. Sound is balanced, battery is great, and they're super lightweight. Only gripe is no ANC, but at this price that's expected. Recommended.", images: [], is_verified_purchase: true, helpful_count: 7, status: "approved", seller_response: null, seller_responded_at: null, created_at: "2026-03-10", updated_at: "2026-03-10", customer: { full_name: "Ayanda W.", avatar_url: null } },
];
